/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface SspButton {
        /**
          * The icon name
         */
        "icon": string;
        /**
          * The button label
         */
        "label": string;
        /**
          * The position of the icon
         */
        "position": string;
        /**
          * The button type ('simple-button', 'button-with-icon', 'button-link' or 'button-link-with-icon')
         */
        "type": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSspButtonElement extends Components.SspButton, HTMLStencilElement {
    }
    var HTMLSspButtonElement: {
        prototype: HTMLSspButtonElement;
        new (): HTMLSspButtonElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "ssp-button": HTMLSspButtonElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface SspButton {
        /**
          * The icon name
         */
        "icon"?: string;
        /**
          * The button label
         */
        "label"?: string;
        /**
          * The event emitter on button click
         */
        "onButtonEvent"?: (event: CustomEvent<boolean>) => void;
        /**
          * The position of the icon
         */
        "position"?: string;
        /**
          * The button type ('simple-button', 'button-with-icon', 'button-link' or 'button-link-with-icon')
         */
        "type"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "ssp-button": SspButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "ssp-button": LocalJSX.SspButton & JSXBase.HTMLAttributes<HTMLSspButtonElement>;
        }
    }
}
